server:
  port: 8080  # ?? ??

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lolposition?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user1
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ??? ?? ? ??? ?? ?? (???)
    show-sql: true        # ??? ???? SQL ??
    properties:
      hibernate:
        format_sql: true  # SQL ?? ?? ??
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false          # HTML ?? ? ?? ?? (?? ???)

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace